services:
  database:
    image: postgres:16-alpine
    container_name: postgres_akk_bot
    env_file:
      - src/app/.env
    environment:
      PGDATA: ./pgdata
    ports:
      - "5432:5432"
    networks:
      - my_app_network
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - my_app_network
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - database

  task-queue:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: task-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - my_app_network


networks:
  my_app_network:
    driver: bridge


volumes:
  pgdata:
    driver: local