"""change_relationship

Revision ID: 1bd2cb63cfaa
Revises: 92f5d08306f0
Create Date: 2025-08-01 18:38:59.221816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd2cb63cfaa'
down_revision: Union[str, Sequence[str], None] = '92f5d08306f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bad_phrases_phrase'), 'bad_phrases', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_bad_phrases_phrase'), 'bad_phrases', ['phrase'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
