"""chancge_Role_field

Revision ID: 1c19df07bec4
Revises: 36e331e483fe
Create Date: 2025-07-22 15:37:53.813790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c19df07bec4'
down_revision: Union[str, Sequence[str], None] = '36e331e483fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(length=64), nullable=False))
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
