"""init

Revision ID: 4896a77c8e8a
Revises: 
Create Date: 2025-08-12 22:53:18.799694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4896a77c8e8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('who_send_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('bad_phrase_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bad_phrase_id'], ['bad_phrases.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['who_send_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.drop_index(op.f('ix_analytics_id'), table_name='russian_roulette_analytics')
    op.drop_table('russian_roulette_analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('russian_roulette_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('who_send_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bad_phrase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bad_phrase_id'], ['bad_phrases.id'], name=op.f('russian_roulette_analytics_bad_phrase_id_fkey')),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('russian_roulette_analytics_chat_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('russian_roulette_analytics_user_id_fkey')),
    sa.ForeignKeyConstraint(['who_send_id'], ['users.id'], name=op.f('russian_roulette_analytics_who_send_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('russian_roulette_analytics_pkey'))
    )
    op.create_index(op.f('ix_analytics_id'), 'russian_roulette_analytics', ['id'], unique=False)
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
