"""any_fix

Revision ID: 54ac64393b91
Revises: 36e331e483fe
Create Date: 2025-07-25 10:18:18.829004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ac64393b91'
down_revision: Union[str, Sequence[str], None] = '69da94d7fe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=128), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
