"""phrase

Revision ID: 733f955136c2
Revises: 6b0913def12f
Create Date: 2025-08-07 12:50:09.359356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733f955136c2'
down_revision: Union[str, Sequence[str], None] = '6b0913def12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bad_phrases_phrase'), 'bad_phrases', ['phrase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bad_phrases_phrase'), table_name='bad_phrases')
    # ### end Alembic commands ###
