"""add_uniq_index

Revision ID: 86994e6dfa00
Revises: 1bd2cb63cfaa
Create Date: 2025-08-01 18:47:14.070449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86994e6dfa00'
down_revision: Union[str, Sequence[str], None] = '1bd2cb63cfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_chat', 'user_chats', ['user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_chat', 'user_chats', type_='unique')
    # ### end Alembic commands ###
