"""phrase

Revision ID: 89142bb07146
Revises: 733f955136c2
Create Date: 2025-08-07 12:59:39.461089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89142bb07146'
down_revision: Union[str, Sequence[str], None] = '733f955136c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bad_phrases_phrase'), table_name='bad_phrases')
    op.create_unique_constraint(None, 'bad_phrases', ['phrase'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bad_phrases', type_='unique')
    op.create_index(op.f('ix_bad_phrases_phrase'), 'bad_phrases', ['phrase'], unique=False)
    # ### end Alembic commands ###
