"""seed bad_phrase

Revision ID: 92f5d08306f0
Revises: cc6722d6f7a1
Create Date: 2025-08-01 15:50:09.285004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f5d08306f0'
down_revision: Union[str, Sequence[str], None] = 'cd40ecdb225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    op.create_unique_constraint("uq_bad_phrases_phrase", "bad_phrases", ["phrase"])
    phrases = [
        "Сделай перерыв @ - сходи нахуй",
        "Пес-борбос и @ нахуй иди",
        "Страх и ненависть в Лас-Вегасе, а @ нахуй идет",
        "@ - пошёл нахуй",
        "Сказка лож, да  @ нахуй пошел",
        "От Волги до Енисея - путь нахуй для @",
        "Через тернии @ идёт нахуй",
        "никто не вечен, @ путь нахуй обеспечен",
        "@ 33 года на печи пролежал, а потом встал и пошёл нахуй.",
        "новая дорога неизвестна, @ по старой нахуй ходит.",
        "не лыком шит @ нахуй спешит",
        "Сделай перерыв @ - сходи нахуй",
        "Я говорю красный свет и @ стоит на месте, я говорю зелёный свет и @ идёт нахуй!",
        "Мороз и солнце; День чудесный! @ идёшь ты нахуй друг прелестный!",
        "Для Вас @ на хуй как на праздник",
        "Сказка ложь, да  @ нахуй пошел",
        "Царский указ: @ идет на хуй!",
        "Без @ и жизнь не та — отправь его нахуй!",
        "Тише едешь — дальше будешь, а @ уже нахуй пришел.",
        "Кто @ ко мне с мечом придет, тот нахуй и уйдет.",
        "Где @, там и ссора, а где ссора — там путь нахуй.",
        "Не имей сто рублей, а имей сто друзей, но @ всё равно нахуй пошли.",
        "Солнце, воздух и вода — лучшие друзья, а @ — лучший друг дороги нахуй.",
        "Семь бед — один ответ: @ нахуй, и всем совет.",
        "Волка ноги кормят, а @ — дорога нахуй.",
        "Любишь кататься — люби и саночки возить, а @ — люби нахуй ходить.",
        "Делу время — потехе час, а @ — время нахуй.",
        "Старый друг @ лучше новых двух, но всё равно нахуй.",
        "Не плюй в колодец — пригодится воды напиться, а @ плюй — всё равно нахуй.",
        "Смех без причины — признак дурачины, а @ без причины — иди нахуй.",
        "В гостях хорошо, а дома лучше, а @ хорошо нахуй.",
        "Кончил дело — гуляй смело, а @ дело — иди нахуй.",
        "Красота спасёт мир, а @ — путь нахуй.",
        "В здоровом теле — здоровый дух, а в теле @ — дорога нахуй.",
        "Слово не воробей — вылетит, не поймаешь, а @ — не воробей, но нахуй улетит.",
        "Я @ тебя породил, я @ и нахуй пошлю.",
        "Век живи — век учись, а @ — век нахуй стремись.",
    ]
    # Формируем bulk insert с ON CONFLICT DO NOTHING
    values_sql = ",\n    ".join(
        f"({sa.text(':phrase' + str(i))}, current_timestamp)"
        for i in range(len(phrases))
    )
    sql = (
        f"INSERT INTO bad_phrases (phrase, updated_at) VALUES\n    {',\n    '.join(['(:phrase' + str(i) + ', current_timestamp)' for i in range(len(phrases))])}\n"
        "ON CONFLICT (phrase) DO NOTHING;"
    )
    params = {f"phrase{i}": phrase for i, phrase in enumerate(phrases)}
    conn.execute(sa.text(sql), params)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
