"""any_changes

Revision ID: b29c91a625b2
Revises: fb4e46b86eb3
Create Date: 2025-07-27 01:36:14.546347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29c91a625b2'
down_revision: Union[str, Sequence[str], None] = 'fb4e46b86eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('private', 'group', 'supergroup', 'channel', name='chattypeenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('user_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_chats_id'), 'user_chats', ['id'], unique=False)
    op.add_column('user_roles', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_user_id_chat_id', 'user_roles', ['user_id', 'chat_id'])
    op.create_foreign_key(None, 'user_roles', 'chats', ['chat_id'], ['id'])
    op.alter_column('users', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint('uq_user_id_chat_id', 'user_roles', type_='unique')
    op.drop_column('user_roles', 'chat_id')
    op.drop_index(op.f('ix_user_chats_id'), table_name='user_chats')
    op.drop_table('user_chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
