"""add

Revision ID: c7520d9aff43
Revises: 86994e6dfa00
Create Date: 2025-08-02 19:16:03.494065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7520d9aff43'
down_revision: Union[str, Sequence[str], None] = '86994e6dfa00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('russian_roulette_analytics', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'russian_roulette_analytics', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'russian_roulette_analytics', type_='foreignkey')
    op.drop_column('russian_roulette_analytics', 'chat_id')
    # ### end Alembic commands ###
