"""add_uniq_index_to_user

Revision ID: fb4e46b86eb3
Revises: 54ac64393b91
Create Date: 2025-07-25 10:38:14.377255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4e46b86eb3'
down_revision: Union[str, Sequence[str], None] = '54ac64393b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_username_chat_id', 'users', ['username', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_username_chat_id', 'users', type_='unique')
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
